### ISSUE TITLE
Automatically add ' | tapout progressbar' ?

### ISSUE THREAD

**Issue by doabit** [rubyworks/minitap#5]
Is there a way to automatically add ' | tapout progressbar' ? I feel it's a bit verbose now. Thanks.

**Comment by trans** [comment]
That, I think, would be rather tricky since it's utilizing a bash pipe.

There are a couple of things you can do though. First, if you are using Rake or another build tool, you can create a task that handles it. Or, you can create your own little bash script that does it. E.g. something like (untested):

``` bash
#!/usr/bin/env sh
if [ -z "$rpt" ]; then
    ruby $@ - --tapy | tapout progressbar
else
    ruby $@ - --tapy | tapout $rpt
fi
```

**Comment by trans** [comment]
For Rake usage you might be interested in this: https://github.com/rubyworks/tapout/wiki/Quick-Start

**Comment by doabit** [comment]
Thanks, i have tried https://github.com/rubyworks/tapout/wiki/Quick-Start, but it can't work well with rails 4, i think to add config like [`Minitest::Reporters.use! Minitest::Reporters::SpecReporter.new`](https://github.com/axskern/minitest-reporters#usage) would be great. then it could work with [spring](https://github.com/jonleighton/spring) or [zeus](https://github.com/burke/zeus).

**Comment by trans** [comment]
I'll have to look into that. Any other info or suggestions you can provide in that regard would be great.

**Comment by doabit** [comment]
Thanks
